# action.yml
name: 'Build RPM Packages'
description: 'Build RPM packages actions'
# inputs:
  # gpgkey_path: 
  #   description: 'Path to the GPG certificate'
  #   required: true
  #   default: ''
  # rpmmacros_path: 
  #   description: 'Path to the RPM Macros file'
  #   required: true
  #   default: ''
  # rpm_path: 
  #   description: 'Path to the RPM files'
  #   required: true
  #   default: ''
  # target_path:
  #   description: 'Default path where the packages should be sent to'
  #   required: true
  #   default: ''
  # target_folder:
  #   description: 'The final folder where the packages should be sent to'
  #   required: true
  #   default: ''
  
# outputs:
#   time: # id of output
#     description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
