name: Deploy to Swarm
description: Deploy/update an image on a Swarm Cluster using Portainer

inputs:
  STACK_NAME:
    required: true

runs:
  using: "composite"
  steps:
    name: "Deploy to a Swarm cluster"
    steps:
      - name: Deploy to Swarm
        run: |
          # Retrieve service spec
          curl -s -H "X-API-Key: ${{env.PORTAINER_API_KEY}}" https://deploy.signalwire.cloud/api/endpoints/${{env.ENDPOINTID}}/docker/services/${{ inputs.STACK_NAME }} > service.spec.json

          # Pull service version from spec (required for update)
          version=$(jq '.Version.Index' service.spec.json)

          # Create request body for service update; Set image tag to tag of newly built image
          jq '.Spec.TaskTemplate.ContainerSpec.Image="${{needs.buildpush.outputs.imagetag}}" | .Spec' service.spec.json > update.spec.json
          # Update the service
          curl -s -X POST -H "X-API-Key: ${{env.PORTAINER_API_KEY}}" https://deploy.signalwire.cloud/api/endpoints/${{env.ENDPOINTID}}/docker/services/${{ inputs.STACK_NAME }}/update?version=$version -d @update.spec.json
        env:
          PORTAINER_API_KEY: ${{ env.PORTAINER_API_KEY }}
          ENDPOINTID: ${{ env.ENDPOINTID }}