name: DependencyTrack dependencies analysys

inputs:
  PROJECT_NAME:
    required: true
    type: string
  PROJECT_VERSION:
    required: true
    type: string
runs:
  using: "composite"
  steps:
    - name: Generaing Bom
      uses: CycloneDX/gh-node-module-generatebom@master
    - uses: DependencyTrack/gh-upload-sbom@v1.0.0
      with:
        serverhostname: ${{ env.DEPENDENCYTRACK_URL }}
        apikey: ${{ env.DEPENDENCYTRACK_APIKEY }}
        projectname: ${{ inputs.PROJECT_NAME }}
        projectversion: ${{ inputs.PROJECT_VERSION }}
        autocreate: true