name: Run Docker compose file
description: Only run docker containers based on compose files

inputs:
  COMPOSE_FILE:
    required: false
    default: provisioning/docker-compose.yml
  RUN_BACKGROUND:
    required: false
    default: 'false'
    
runs:
  using: "composite"
  steps:
  - name: Login to DockerHub
    uses: docker/login-action@v2
    with:
      username: ${{ env.DOCKERHUB_USERNAME }}
      password: ${{ env.DOCKERHUB_TOKEN }}

  - uses: KengoTODA/actions-setup-docker-compose@main
    with:
      version: '2.12.1'

  - name: Create default network  
    run: docker network create signalwire_freeswitch
    shell: bash

  - name: Run docker-compose
    if: inputs.RUN_BACKGROUND == 'false'
    run: docker-compose -f ${{ inputs.COMPOSE_FILE }} up 
    shell: bash
  # - uses: isbang/compose-action@v1.4.1
  #   with:
  #     compose-file: ${{inputs.COMPOSE_FILE}}
  #   env:
  #     BUILD_NUMBER: ${{ env.GITHUB_RUN_NUMBER }}
  #     HASH: ${{ env.GITHUB_SHA }}
