name: Run Docker compose file
description: Buld and push image to SignalWire registry

inputs:
  COMPOSE_FILE:
    required: false
    default: provisioning/docker-compose.yml
    
runs:
  using: "composite"
  steps:
  - uses: KengoTODA/actions-setup-docker-compose@main
    with:
      version: '2.12.1'
  - name: Run docker-compose
    run: docker-compose -f ${{ inputs.COMPOSE_FILE }} up -d
    shell: bash