name: Kubectl statics deploy

inputs:
  STATICS_PATH:
    required: true
    type: string
env:    
  KUBECONFIG:
    required: false
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@master
    - name: deploy to cluster
      uses: danielr1996/kubectl-action@1.0.0
      with:
        command: apply -f ${{ inputs.STATICS_PATH }}
        config: ${{ env.KUBECONFIG }}
