name: Kubectl statics deploy

inputs:
  STATICS_PATH:
    required: true
    type: string
env:    
  KUBECONFIG:
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@master
    - name: deploy to cluster
      uses: ghostzero/kubectl@v1
      env:
        KUBE_CONFIG_DATA: '${{ env.KUBECONFIG }}'
      with:
        args: apply -f ${{ inputs.STATICS_PATH }}
