name: Kubectl statics deploy

inputs:
  STATICS_PATH:
    required: true
    type: string
env:    
  KUBECONFIG:
    required: false
runs:
  # using: "composite"
  steps:
    - uses: actions/checkout@master
    - name: deploy to cluster
      uses: steebchen/kubectl@v2.0.0
      with:
        command: apply -f ${{ inputs.STATICS_PATH }}
        config: ${{ secrets.KUBECONFIG_STAGING_DO_NYC1_COCRE_SUP }} 
