name: Ruby Unit Test
description: Ruby Unit Test report


inputs:
  RUBY_VERSION:
    required: false
    default: "2.7.4"

runs:
  using: "composite"
  steps:
    - name: Setup Ruby and install gems
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
        version: ${{ inputs.RUBY_VERSION }}

    - name: Run Tests
      run: |
        cp .env.example .env
        bundle install --path ./bundle --without production,development > /dev/null
        bundle exec rake db:test:prepare > /dev/null
        bundle exec rake core:db:test:prepare > /dev/null
        bundle exec rake messaging:db:test:prepare > /dev/null
        bundle exec rspec -f j -o tmp/rspec_results.json -f p
      shell: bash
    
    - name: RSpec Report
      uses: SonicGarden/rspec-report-action@v2
      with:
        token: ${{ env.GITHUB_TOKEN }}
        json-path: tmp/rspec_results.json
      if: always()
