name: Ruby Unit Test
description: Ruby Unit Test report


inputs:
  RUBY_VERSION:
    required: false
    default: "2.7.6"
    description: "Default Ruby version"

runs:
  using: "composite"
  steps:
    - name: Setup dependencies
      run: sudo apt update ; sudo install libpq-dev -y
      shell: bash

    # - name: Setup Ruby and install gems
    #   uses: ruby/setup-ruby@v1
    #   with:
    #     bundler-cache: true
    #     ruby-version: ${{ inputs.RUBY_VERSION }}

    - uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-

    - name: Run Tests
      run: |
        cp .env.example .env
        bundle config set gems.contribsys.com $CONTRIBSYS_CREDENTIALS
        bundle install --path ./bundle --without production,development 
        bundle exec rake db:test:prepare 
        bundle exec rake core:db:test:prepare 
        bundle exec rake messaging:db:test:prepare 
        bundle exec rspec -f j -o tmp/rspec_results.json -f p
      shell: bash
      env:
        CONTRIBSYS_CREDENTIALS: ${{ env.CONTRIBSYS_CREDENTIALS }}
    
    - name: RSpec Report
      uses: SonicGarden/rspec-report-action@v2
      with:
        token: ${{ env.GITHUB_TOKEN }}
        json-path: tmp/rspec_results.json
