name: Code scan
description: Code vulnerability assessment

runs:
  using: "composite"
  steps:
  - name: Run AppScan CodeSweep
    uses: HCL-TECH-SOFTWARE/appscan-codesweep-action@v2
    with:
      asoc_key: ${{env.ASOC_KEY}}
      asoc_secret: ${{env.ASOC_SECRET}}
    env: 
      GITHUB_TOKEN: ${{env.GITHUB_TOKEN}}