name: Snyk scan
description: Snyk docker container vulnerability assessment

runs:
  using: "composite"
  steps:
  - name: Run Snyk to check Docker image for vulnerabilities
    uses: snyk/actions/docker@master
    env:
      SNYK_TOKEN: ${{ env.SNYK_TOKEN }}
    with:
      image: ${{ env.IMAGE }}
        
