name: Trivy scan
description: Trivy docker container vulnerability assessment

inputs:
  IMAGE:
    required: true
    
runs:
  using: "composite"
  steps:
  - name: Run Trivy vulnerability scanner
    uses: aquasecurity/trivy-action@master
    with:
      image-ref: ${{ inputs.IMAGE }}
      format: 'sarif'
      output: 'trivy-results.sarif'

  - uses: lazy-actions/gitrivy@v2
    with:
      token: ${{ env.GITHUB_TOKEN }}
      image: ${{ inputs.IMAGE }}
      severity: LOW