name: Trivy scan
description: Trivy docker container vulnerability assessment

inputs:
  IMAGE:
    required: true
    
runs:
  using: "composite"
  steps:
  - name: Run Trivy vulnerability scanner
    uses: aquasecurity/trivy-action@master
    with:
      image-ref: ${{ inputs.IMAGE }}
      format: 'sarif'
      output: 'trivy-results.sarif'

  # - name: Upload Trivy scan results to GitHub Security tab
  #   uses: github/codeql-action/upload-sarif@v1
  #   with:
  #     sarif_file: 'trivy-results.sarif'      
  - uses: knqyf263/trivy-issue-action@v0.0.3
    # with:
    #   # Label name
    #   # Default: vulnerability (this label must be created in advance)
    #   label: ''

    #   # Severities of vulnerabilities to be registered to GitHub Issues
    #   # Default: 'CRITICAL'
    #   severity: ''
      
    #   # Comma separated list of directories where traversal is skipped
    #   # Default: ''
    #   # Example: 'tests, integration-tests'
    #   skip-dirs: ''

    #   # Assignees
    #   # Default: ''
    #   # Example: 'monalisa,hubot'
    #   assignee: ''

    #   # Project ID to which the created Issue will be tied.
    #   # Default: ''
    #   project-id: ''
