# This is a basic workflow to help you get started with Actions

name: Sign and Distribute RPM Packages

# Controls when the workflow will run
on:

  workflow_call:
    inputs:
      ENVIRONMENT:
        required: false
        type: string
      RUNNER:
        required: false
        default: self-hosted
        type: string
      TARGET_PATH:
        required: true
        default: ''
        type: string
      TARGET_FOLDER:
        required: true
        default: ''
        type: string
      GPG_NAME:
        required: true
        default: ''
        type: string
      PROXY_URL:
        required: true
        type: string
      EXEC_COMMANDS:
        required: false
        type: string
        description: 'whenever you would like to execute commands on remote'
      FILES:
        type: string
        required: false
        description: 'Files to move to remote host'
      FILES_FOLDER:
        type: string
        required: false
        description: 'Files target folder'
      HOSTNAME:
        type: string
        required: false
        description: 'Hostname to connect to.'
    secrets:
      GPG_KEY:
        required: true
      GPG_CERT:
        required: true
      TELEPORT_TOKEN:
        required: false

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:

    # The type of runner that the job will run on
    runs-on: ${{ inputs.RUNNER }}
    name: Sign And Distribute Packages
    environment: ${{ inputs.ENVIRONMENT }}

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - uses: actions/download-artifact@v2
      with:
        name: rpm-artifact

    - name: GPG Key Secret File
      uses: ttd2089/secret-file-action@main
      id: gpg-key-secret
      with:
        secret: ${{ secrets.GPG_KEY }}
        b64-decode: true 
    
    - name: GPG Key Secret File
      uses: ttd2089/secret-file-action@main
      id: gpg-cert-secret
      with:
        secret: ${{ secrets.GPG_CERT }}
        b64-decode: true 

    - name: Sign RPM
      uses: signalwire/sign-rpm-packages-action@dev
      with:
        gpgkey_file: ${{ steps.gpg-key-secret.outputs.file }}
        gpgcert_file: ${{ steps.gpg-cert-secret.outputs.file }}
        gpg_name: ${{inputs.GPG_NAME }}
        target_path: ${{ inputs.TARGET_PATH }}
        target_folder: ${{ inputs.TARGET_FOLDER }}
        rpm_path: .

    - name: Copy files to remote host
      uses: ./actions/.github/actions/teleport
      with:
        PROXY_URL: ${{ inputs.PROXY_URL }}
        FILES: ${{ inputs.FILES }}
        USERNAME: ${{ inputs.USERNAME }}
        HOSTNAME: ${{ inputs.HOSTNAME }}
        EXEC_COMMANDS: ${{ inputs.EXEC_COMMANDS }}
      env: 
        TOKEN: ${{ secrets.TELEPORT_TOKEN }}
