# This is a basic workflow to help you get started with Actions

name: Sign and Distribute RPM Packages

# Controls when the workflow will run
on:

  workflow_call:
    inputs:
      ENVIRONMENT:
        required: false
        type: string
      RUNNER:
        required: false
        default: self-hosted
        type: string
      TARGET_PATH:
        required: true
        default: ''
        type: string
      TARGET_FOLDER:
        required: true
        default: ''
        type: string
      GPG_NAME:
        required: true
        default: ''
        type: string
    secrets:
      GPG:
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:

    # The type of runner that the job will run on
    runs-on: ${{ inputs.RUNNER }}
    name: Sign And Distribute Packages
    environment: ${{ inputs.ENVIRONMENT }}

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Checkout actions
      uses: actions/checkout@v3
      with:
        repository: signalwire/actions-template
        ref: feat/packages
        path: actions

    - name: GPG Key Secret File
      uses: ttd2089/secret-file-action@main
      id: gpg-key-secret
      with:
        secret: ${{ secrets.GPG }}
        b64-decode: false 

    - uses: actions/download-artifact@v2
      with:
        name: rpm-artifact

    - name: Signing Packages
      uses: ./actions/.github/actions/sign-package-action
      with:
        gpg_file: ${{ steps.gpg-key-secret.outputs.file }}
        gpg_name: ${{inputs.GPG_NAME }}
        target_path: ${{ inputs.TARGET_PATH }}
        target_folder: ${{ inputs.TARGET_FOLDER }}
        rpm_path: .