# This is a basic workflow to help you get started with Actions

name: Build RPM Packages

# Controls when the workflow will run
on:

  workflow_call:
    inputs:
      ENVIRONMENT:
        required: false
        type: string
      RUNNER:
        required: false
        default: self-hosted
        type: string
      COMPOSE_FILE:
        required: true
        type: string
    secrets:
      DOCKERHUB_USERNAME:
        required: false
      DOCKERHUB_TOKEN:
        required: false

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    # permissions:
      # id-token: write
      # contents: read

    # The type of runner that the job will run on
    runs-on: ${{ inputs.RUNNER }}
    name: Build
    environment: ${{ inputs.ENVIRONMENT }}

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Checkout actions
      uses: actions/checkout@v3
      with:
        repository: signalwire/actions-template
        ref: main
        path: actions
        
    - name: Build RPM
      uses: ./actions/.github/actions/build-rpm-action
      # with:
      #   COMPOSE_FILE: ${{ inputs.COMPOSE_FILE }}
      # env:
      #   DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      #   DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

    - uses: actions/upload-artifact@v2
      with:
        name: rpm-artifact
        path: ./export