# This is a basic workflow to help you get started with Actions

name: Build RPM Packages

# Controls when the workflow will run
on:

  workflow_call:
    inputs:
      ENVIRONMENT:
        required: false
        type: string
      RUNNER:
        required: false
        default: self-hosted
        type: string
      PROJECT_NAME:
        required: true
        type: string
    secrets:
      DOCKERHUB_USERNAME:
        required: false
      DOCKERHUB_TOKEN:
        required: false

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    # permissions:
      # id-token: write
      # contents: read

    # The type of runner that the job will run on
    runs-on: ${{ inputs.RUNNER }}
    name: Build
    environment: ${{ inputs.ENVIRONMENT }}

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Checkout actions
      uses: actions/checkout@v3
      with:
        repository: signalwire/actions-template
        ref: feat/packages
        path: actions
        
    - name: compose
      uses: ./actions/.github/actions/docker-compose
      with:
        COMPOSE_FILE: ${{ inputs.COMPOSE_FILE }}
    # - name: Build RPM
    #   with:
    #     project_name: ${{ inputs.PROJECT_NAME }}
    #   # env:
    #   #   DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
    #   #   DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

    - run: mkdir export ; mv *.rpm export

    - uses: actions/upload-artifact@v2
      with:
        name: rpm-artifact
        path: ./export