# This is a basic workflow to help you get started with Actions

name: Build RPM Packages

# Controls when the workflow will run
on:

  workflow_call:
    inputs:
      ENVIRONMENT:
        required: false
        type: string
      RUNNER:
        required: false
        default: self-hosted
        type: string
      COMPOSE_FILE:
        required: true
        type: string
      RUN_BACKGROUND:
        required: false
        type: string
        default: 'false'
    secrets:
      DOCKERHUB_USERNAME:
        required: false
      DOCKERHUB_TOKEN:
        required: false

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:

    runs-on: ${{ inputs.RUNNER }}
    name: Build
    environment: ${{ inputs.ENVIRONMENT }}

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Build RPM Packages
      uses: signalwire/build-rpm-packages-action@v0.1

      with:
        COMPOSE_FILE: ${{ inputs.COMPOSE_FILE }}
        RUN_BACKGROUND: 'false'
        DOCKERHUB_LOGIN: 'false'
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

    - uses: actions/upload-artifact@v2
      with:
        name: rpm-artifact
        path: |
          *.rpm