# This is a basic workflow to help you get started with Actions

name: CI checking

# Controls when the workflow will run
on:

  workflow_dispatch:
    inputs:
      PROJECT_NAME:
        required: true
        type: string
      DOTNET-VERSION:
        required: false
        default: "3.1.402"
        type: string
      LANGUAGE:
        required: true
        type: string
      NODE_VERSION:
        required: false
        default: "19"
        type: string
      COVERAGE:
        required: false
        type: boolean
        default: true
    secrets:
      SONAR_HOST_URL:
        required: false
      SONAR_TOKEN: 
        required: false
      
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy"
  ci:
    # The type of runner that the job will run on
    runs-on: [ self-hosted ]
    name: CI_CHECK

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Checkout actions
      uses: actions/checkout@v3
      with:
        repository: signalwire/actions-template
        ref: dev
        path: actions

    - name: Test JS
      if:  github.event.inputs.LANGUAGE == 'JavaScript'
      uses: ./actions/.github/actions/test-javascript
      with:
        NODE_VERSION: ${{ inputs.NODE_VERSION }}
    
    - name: SonarQube Coverage
      if: github.event.inputs.COVERAGE != false
      uses: ./actions/.github/actions/sonarqube
      env:
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

