# This is a basic workflow to help you get started with Actions

name: CI checking

# Controls when the workflow will run
on:

  workflow_call:
    inputs:
      PROJECT_NAME:
        required: true
        type: string
    secrets:
      SONAR_HOST_URL:
        required: true
      SONAR_TOKEN: 
        required: true
      
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy"
  ci:
    # The type of runner that the job will run on
    runs-on: [ self-hosted ]
    name: CI_CHECK

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@master
      env:
        SONAR_TOKEN: ${{ env.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ env.SONAR_HOST_URL }}
    # - name: SonarQube Quality Gate check
    #   if: ${{ inputs.BUILD_BREAKER }} == true
    #   uses: sonarsource/sonarqube-quality-gate-action@master
    #   # Force to fail step after specific time
    #   with:
    #     timeout-minutes: 5
    #   env:
    #    SONAR_TOKEN: ${{ env.SONAR_TOKEN }}