# This is a basic workflow to help you get started with Actions

name: Swarm Deplou

# Controls when the workflow will run
on:

  workflow_call:
    inputs:
      STACK_NAME:
        required: true
        type: string
      APPROVERS:
        required: false
        type: string
    secrets:
      ENDPOINTID:
        required: false
      PORTAINER_API_KEY:
        required: false
      GH_APPROVAL_APP_ID:
        required: false
      GH_APPROVAL_APP_PKEY:
        required: false

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest 
    name: Build

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - uses: ./actions/.github/actions/approval
      name: Request approval
      if: ${{ inputs.APPROVERS != null }}
      env:
        GH_APPROVAL_APP_ID: ${{ secrets.GH_APPROVAL_APP_ID }}
        GH_APPROVAL_APP_PKEY: ${{ secrets.GH_APPROVAL_APP_PKEY }}
      with:
        APPROVERS: ${{ inputs.APPROVERS }}
    
    - uses: ./actions/.github/actions/swarm-deploy
      name: Deploy to a Swarm Cluster
      env:
        PORTAINER_API_KEY: ${{ secrets.PORTAINER_API_KEY }}
        ENDPOINTID: ${{ secrets.ENDPOINTID }}
      with:
        STACK_NAME: ${{ inputs.STACK_NAME }}


