on:
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request. 
  push:
    branches:
      - master
  pull_request:
      types: [opened, synchronize, reopened]

name: Main Workflow
jobs:
  sonarqube:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - name: Setup sonarqube
      uses: warchant/setup-sonar-scanner@v3
    - name: Run sonarqube
      run: sonar-scanner
           -Dsonar.organization=signalwire 
           -Dsonar.projectKey=signalwire_actions-template_AYRieeZ2aGLrYeLIXEXM
           -Dsonar.sources=.
           -Dsonar.host.url=http://35.196.153.159:9000
           -Dsonar.login=${{ secrets.SONAR_TOKEN }}
    - name: SonarQube Quality Gate check
      # if: ${{ inputs.BUILD_BREAKER }} == true
      uses: sonarsource/sonarqube-quality-gate-action@master
      # Force to fail step after specific time
      timeout-minutes: 5
      env:
       SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}